@startuml
Title Fog Carport - to be
|Customer|
start
:Go to website;
|#AntiqueWhite|Webshop|
:Present options;
|Customer|
: Choose Customize carport;
:Select dimensions;
|Webshop|
repeat
:Verifying measures;
repeat while (Measures doable?) is (no)
->yes;
|Customer|
:Place Order/pay;
|Webshop|
:Generate bill of materials and order in DB;
repeat
:Verify payment/verify order manually;
|Fog|
:Go through customers inquery/order;
:Contact cusmtomer for customer service and aditional information;
repeat while (Everything ok?) is (no)
->yes;
|Webshop|
:Order placed;
:Make receipt/manual;
fork
|Customer|
:Reciept/manual]
:Wait for materials (and construction crew);
fork again
|Fog|
:Pack the materials;
:Deliver the materials;
|Customer|
end fork
:Recieve materials/Construnction Crew;
stop
@endum