@startuml
Title Fog Carport - as is
|Customer|
start
:Go to website;
|#AntiqueWhite|Webshop|
:Present options;
|Customer|
: Choose Customize carport;
:Select dimensions;
|Webshop|
repeat
:Calculating/Verifying measures;
repeat while (Measures doable?) is (no)
->yes;
:Give customer an overview of carport;
|Customer|
:Recieve overview;
:Place Order/pay;
|Webshop|
repeat
:verify order manually;
|Fog|
:Go through customer's order;
repeat while (Everything ok?) is (no)
->yes;
|Webshop|
:Order placed;
:Make receipt/manual;
fork
|Customer|
:Reciept/manual]
:Wait for materials (and construction crew);
fork again
|Fog|
:Pack the materials;
:Deliver the materials;
|Customer|
end fork
:Recieve materials/Construnction Crew;
stop
@enduml