@startuml
Title Fog Carport
|Customer|
start
:Go to website;
|#AntiqueWhite|Webshop|
:Precent options;
|Customer|
: Choose Customize carport;
:Input preferncences;
|Webshop|
repeat
:Calculating/Verifying measures;
repeat while (Measures doable?) is (no)
->yes;
:Give customer an overview of carport;
|Customer|
:Recieve overview;
:Place Order/pay;
|Webshop|
repeat
:Verify payment/verify order manually;
|Fog|
:Go through customers inquery/order;
:Contact cusmtomer for customer service and aditional information;
repeat while (Everything ok?) is (no)
->yes;
|Webshop|
:Order placed;
:Make receipt/manual/plukklist;
fork
|Customer|
:Reciept/Manual/plukkliste]
:Wait for materials (and construction crew);
fork again
|Fog|
:Pack the materials;
:Deliver the materials;
|Customer|
end fork
:Recieve materials/Construnction Crew;
stop
@enduml